<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $escaper \Magento\Framework\Escaper */
/** @var $configProvider \Magento\Search\ViewModel\ConfigProvider */
$configProvider = $block->getData('configProvider');
/** @var $versionManager \Magento\Search\ViewModel\AdditionalSearchFormData */
$additionalSearchFormData = $block->getData('additionalSearchFormData');
/** @var $helper \Magento\Search\Helper\Data */
$helper = $configProvider->getSearchHelperData();
$quickSearchUrl = $escaper->escapeUrl($helper->getSuggestUrl());
?>
<div class="block-search-anime">
    <div class="block-content-anime">
        <form class="form-anime minisearch-anime" id="search_mini_form-anime"
            action="<?= $escaper->escapeUrl($helper->getResultUrl()) ?>" method="get">

            <div class="field-anime search-anime">

                <div class="control">
                    <input id="search"
                        data-mage-init='{
                            "quickSearch": {
                                "formSelector": "#search_mini_form",
                                "url": "<?= /* @noEscape */ $quickSearchUrl ?>",
                                "destinationSelector": "#search_autocomplete",
                                "minSearchLength": "<?= $escaper->escapeHtml($helper->getMinQueryLength()) ?>"
                            }
                        }'
                        type="text"
                        name="<?= $escaper->escapeHtmlAttr($helper->getQueryParamName()) ?>"
                        value="<?= /* @noEscape */ $helper->getEscapedQueryText() ?>"
                        placeholder="<?= $escaper->escapeHtmlAttr(__('Search entire store here...')) ?>"
                        class="input-text"
                        maxlength="<?= $escaper->escapeHtmlAttr($helper->getMaxQueryLength()) ?>"
                        role="combobox"
                        aria-haspopup="false"
                        aria-autocomplete="both"
                        autocomplete="off"
                        aria-expanded="false" />
                    <div id="search_autocomplete" class="search-autocomplete"></div>

                </div>
            </div>
            
                <button type="submit"
                    title="<?= $escaper->escapeHtml(__('Search')) ?>"
                    class="anime-search-button"
                    aria-label="Search">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="w-6 h-6" height="25" width="25" data-astro-cid-mjrxwznw="" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z"></path>
                    </svg>
                </button>
           
        </form>
    </div>
</div>