<div class="anime-hero-container">
    <video class="anime-hero-video" autoplay="" loop="" muted="" playsinline="">
        <source src="https://anime-kingdom-market.co.uk/static/version1735397606/frontend/AnimeKingdom/AnimeTheme/en_GB/video/en_GB/vegeta.mp4" type="video/mp4">
        Your browser does not support the video tag.
    </video>
    <div class="hero-left">
        <div class="hero-left-first">
            Boost Your Anime Collection!
        </div>
        <div class="hero-left-second">
            Offer! <br>Dragon Ball Items!
        </div>
        <div class="hero-left-third">
            Grab Your Favorites at Unbeatable Prices!
        </div>
        <div class="hero-left-fourth">
            <span class="hero-left-fourth-panel">25% OFF</span>

        </div>
        <div class="hero-left-fifth">
            anime-kingdom-market.co.uk
        </div>
    </div>
    <div class="hero-right"></div>
</div>


